---
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: Import apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present
  become: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present
  become: yes

- name: Create docker group
  group:
    name: docker
    state: present
  become: yes

- name: Append user in docker group
  user:
    name: "{{docker_user}}"
    groups: docker
    append: yes
  become: yes

- name: Configure Docker to start on boot
  systemd:
    name: docker
    enabled: yes
