---
- hosts: localhost
  roles:
    - { role: cmprescott.chrome, become: yes }
    - chromium
    - fbreader
    - { role: youtubedl, become: yes }
    - { role: mpv, become: yes }
    - { role: mediatags, become: yes }
    - { role: php-coder.oraclejdk, become: yes }
    - desktop
    - { role: phpstorm, tags: phpstorm }
    - { role: atom, become: yes }
    - git
    - terminal
    - goldendict
    - vim
    - docker
    - scripts
    - i3

